name: echo-ai

channels:
    - anaconda
    - pytorch

dependencies:
    - python==3.7
    - pytorch
    - pip:
        - Keras==2.2.4
        - Keras-Applications==1.0.8
        - Keras-Preprocessing==1.1.0
        - protobuf==3.8.0
        - PyYAML==5.1.1
        - tensorflow==1.14.0
        - tensorflow-estimator==1.14.0
